name: Build
on:
  push:
    branches:
      - master
    pull_request:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Download dependencies
        run: go mod download

      - name: Build
        run: go build -v -o gop .

      - name: Test
        run: go test -race ./...